name = "portal"
description = "Ada SDL/GLFW alternative"

version = "0.1.0-dev"
authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <henley@adacore.com>"]
maintainers-logins = ["ohenley"]
licenses = "Apache-2.0"
website = "https://github.com/GNAT-Academic-Program/portal"
tags = ["windowing", "input", "framebuffer", "sdl", "glfw", "spark", "gap"]

project-files = ["portal.gpr"]
